### ISSUE TITLE
Would love some 'Interviewer' question list

### ISSUE THREAD

**Issue by adityaraute** [bob-fornal/work-notes#2]
https://github.com/bob-fornal/work-notes/blob/main/Interviewing/README.md#interviewer

If this section were populated with some common interviewer questions specific to the target audience, it may be beneficial

**Comment by bob-fornal** [comment]
I could add more. There are a lot of options out there. This repository is specifically for my notes and documentation. I'll keep this in mind as I'm reviewing content and may add some information here.

**Comment by adityaraute** [comment]
Oh my bad, I misunderstood the purpose. 
I'll close the issue.
